### ISSUE TITLE
Pretrained models on coco

### ISSUE THREAD

**Issue by MalharJ** [microsoft/robust-models-transfer#1]
Will the pretrained models for the MS coco dataset be available?

**Comment by lengstrom** [comment]
They'll be available mid October!

**Comment by lengstrom** [comment]
(At latest)

**Comment by runopti** [comment]
Looks like pretrained models on COCO are still missing? Any chance you could upload the weights?

**Comment by lengstrom** [comment]
Solved in https://github.com/microsoft/robust-models-transfer/issues/10
