### ISSUE TITLE
Failed to download models

### ISSUE THREAD

**Issue by mzweilin** [microsoft/robust-models-transfer#12]
Hi there,

I tried to download some pretrained models, but failed. Could you please fix the links at https://github.com/microsoft/robust-models-transfer#download-our-robust-imagenet-models ?

`AuthenticationFailedServer failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:95671a2b-401e-000b-0d30-ba8434000000 Time:2021-10-05T21:32:40.6862769ZSignature not valid in the specified time frame: Start [Wed, 10 Jun 2020 07:06:23 GMT] - Expiry [Tue, 05 Oct 2021 15:06:23 GMT] - Current [Tue, 05 Oct 2021 21:32:40 GMT]`

**Comment by Hadisalman** [comment]
@mzweilin I have just fixed the links. You should be able to download all our models now!

**Comment by mzweilin** [comment]
Thanks @Hadisalman
