### ISSUE TITLE
Failed to download pretrained models.

### ISSUE THREAD

**Issue by csjunjun** [microsoft/robust-models-transfer#16]
![image](https://github.com/microsoft/robust-models-transfer/assets/8732743/fef95634-fcfe-413b-8260-4b4df211a524)
Hi, could you please help fix this link?
Thank you so much~!

**Comment by Hadisalman** [comment]
@csjunjun @WHYwyh will fix this soon.

**Comment by Hadisalman** [comment]
@csjunjun @WHYwyh I fixed the links! They should work now. Also we are now hosting all these robust models on huggings face [here](https://huggingface.co/madrylab/robust-imagenet-models).

**Comment by WHYwyh** [comment]
Thanks a lot. However, it seems that the links to the datasets are also broken. Could you please take a moment to fix them?

**Comment by csjunjun** [comment]
Thank you very much~!
