### ISSUE TITLE
How to load ImageNet models in Tensorflow using these weights

### ISSUE THREAD

**Issue by vikxoxo** [microsoft/robust-models-transfer#5]
Hi,

Kindly someone may show how to load an ImageNet model in tensorflow having the provided weights.
I tried following things:
* provided the path to the provided weights in the Tensorflow weights argument. 
* tried model.load_weights()
All of the things are saying error: 
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

**Comment by andrewilyas** [comment]
Sorry, this repo was designed for use with PyTorch only. The only way I can think of to use TF would be to load the weights in PyTorch and then use standard conversion techniques between PyTorch and TF (e.g. ONNX), but we have no expertise there.
