### ISSUE TITLE
Error loading Mnasnet pre-trained model

### ISSUE THREAD

**Issue by kiranchari** [microsoft/robust-models-transfer#6]
Thanks for sharing this neat codebase.

I am trying to load the MNASNET pre-trained model and get the following assertion error from pytorch. It looks related to the MNASNET version that is being loaded. I am not familiar with this architecture so let me know if this issue belongs in the pytorch forums instead. 

Thank you.

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-75-299c44a23ecf> in <module>
     37 
     38 for m in pre_trained_model_names:
---> 39     model, _ = model_utils.make_and_restore_model(
     40             arch=models.mnasnet1_0(False),
     41             dataset=datasets.ImageNet(''),

~/miniconda3/envs/robust-transfer/lib/python3.8/site-packages/robustness/model_utils.py in make_and_restore_model(arch, dataset, resume_path, parallel, pytorch_pretrained, add_custom_forward, *_)
    100         sd = checkpoint[state_dict_path]
    101         sd = {k[len('module.'):]:v for k,v in sd.items()}
--> 102         model.load_state_dict(sd)
    103         print("=> loaded checkpoint '{}' (epoch {})".format(resume_path, checkpoint['epoch']))
    104     elif resume_path:

~/miniconda3/envs/robust-transfer/lib/python3.8/site-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1207                     load(child, prefix + name + '.')
   1208 
-> 1209         load(self)
   1210         del load
   1211 

~/miniconda3/envs/robust-transfer/lib/python3.8/site-packages/torch/nn/modules/module.py in load(module, prefix)
   1205             for name, child in module._modules.items():
   1206                 if child is not None:
-> 1207                     load(child, prefix + name + '.')
   1208 
   1209         load(self)

~/miniconda3/envs/robust-transfer/lib/python3.8/site-packages/torch/nn/modules/module.py in load(module, prefix)
   1205             for name, child in module._modules.items():
   1206                 if child is not None:
-> 1207                     load(child, prefix + name + '.')
   1208 
   1209         load(self)

~/miniconda3/envs/robust-transfer/lib/python3.8/site-packages/torch/nn/modules/module.py in load(module, prefix)
   1201         def load(module, prefix=''):
   1202             local_metadata = {} if metadata is None else metadata.get(prefix[:-1], {})
-> 1203             module._load_from_state_dict(
   1204                 state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
   1205             for name, child in module._modules.items():

~/miniconda3/envs/robust-transfer/lib/python3.8/site-packages/torchvision/models/mnasnet.py in _load_from_state_dict(self, state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
    169                               missing_keys: List[str], unexpected_keys: List[str], error_msgs: List[str]) -> None:
    170         version = local_metadata.get("version", None)
--> 171         assert version in [1, 2]
    172 
    173         if version == 1 and not self.alpha == 1.0:

AssertionError:

**Comment by Hadisalman** [comment]
Hi @kiranchari!

Yeah I believe it is better to post this in PyTorch's forums. It is specific to the architecture, not our code base.

Thanks!
Hadi
