### ISSUE TITLE
Request about code of training models on ImageNet

### ISSUE THREAD

**Issue by RuiFeiHe** [microsoft/robust-models-transfer#8]
Hi, I'm wondering how I could use your codebase to train a model from scratch on ImageNet as pretrained one. Could you please share the code or if I'm missing something?

**Comment by Hadisalman** [comment]
To train ImageNet models from scratch, you can follow [this part](https://github.com/microsoft/robust-models-transfer#running-transfer-learning-experiments) of the README, and simply replace `--dataset cifar10` by `--dataset imagenet`.

Now, if you want to start from a pretrained ImageNet model, you can add `--pytorch-pretrained` to your command.

Hope this helps!

**Comment by RuiFeiHe** [comment]
Thanks!
